import type { NextPage } from 'next'
import Head from 'next/head'
import AuthBanner from '../components/AuthBanner'
import ShiftHistory from '../components/ShiftHistory/ShiftHistory'
import ShitTimer from '../components/ShiftTimer/ShitTimer'
import  { Container } from './styles.js';


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Shift App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='p-10'>
        <Container>
          <div className='top-banner'>
            <h1 className='text-2xl font-bold'>
              Shift App
              <p className='my-3'>
                Track your shifts.
              </p>
            </h1>
            <AuthBanner />
          </div>
        </Container>
        <ShitTimer />
        <ShiftHistory />
      </main>
    </div>
  )
}

export default Home
